# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f7eaae61fa01e8a6a281fa846ee9b9fdd117036f00c42425e937c9161b37b054e49a234b09f06af15568cd19f40f68a493546332741c3f233f7ec70427f9f1d

test:
  secret_key_base: 19f9d3ac7fce0f4924e64078736d54726e227234dca6b307fbdd156cd968e0b02b2f33ef46ca488bf1f7bd7dcecdd6ab1582b4ec997f88bc8be7a549b00df5bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
